language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install --upgrade -r requirements.txt -r test/requirements_tests.txt"
script:
  - "pytest"
  - "pylint hbp_service_client"
  - "pycodestyle hbp_service_client --max-line-length 100"
